trigger:
- main  # Adjust this to the branch you want to monitor in Azure DevOps.

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout code from Azure DevOps
- task: Checkout@1
  displayName: "Checkout code from Azure Repos"
  inputs:
    clean: true

# Step 2: Install Git (if necessary) using PowerShell
- task: PowerShell@2
  displayName: "Install Git"
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install -y git

# Step 3: Configure GitHub credentials
- task: PowerShell@2
  displayName: "Set GitHub credentials"
  inputs:
    targetType: 'inline'
    script: |
    echo "The value of my variable is: $(GitHubToken)"
      git config --global user.name "spucelik"
      git config --global user.email "spucelik@hotmail.com"
      git remote add origin https://$(GitHubToken)@github.com/Spucelik/Split-pages-from-a-document.git
  env:
    GitHubToken: $(GitHubToken)  # Use the secret token securely

# Step 4: Push changes to GitHub
- task: PowerShell@2
  displayName: "Push changes to GitHub"
  inputs:
    targetType: 'inline'
    script: |
      git add .
      git commit -m "Automated commit from Azure DevOps pipeline"
      git push origin main
  env:
    GitHubToken: $(GitHubToken)  # Use the secret token securely
