trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:


# Step 3: Configure Git User Information
- task: PowerShell@2
  displayName: "Set Git User Information"
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.name "spucelik"
      git config --global user.email "steve@pucelik,.net"

# Step 4: Add GitHub Remote
- task: PowerShell@2
  displayName: "Add GitHub Remote"
  inputs:
    targetType: 'inline'
    script: |
      git remote add origin https://$(GitHubToken)@github.com/Spucelik/Split-pages-from-a-document.git
  env:
    GitHubToken: $(GitHubToken)

# Step 5: Commit and Push Changes to GitHub
- task: PowerShell@2
  displayName: "Initial Commit to GitHub (if necessary)"
  inputs:
    targetType: 'inline'
    script: |
      # Ensure a README.md file exists to avoid pushing an empty repository
      if [ ! -f README.md ]; then
        echo "# Split-pages-from-a-document" > README.md
        git add README.md
      fi

      # Commit and push changes to main branch
      git commit -m "Initial commit" || echo "No changes to commit"
      git branch -M main
      git push -u origin main
  env:
    GitHubToken: $(GitHubToken)
