trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:


# Step 3: Configure Git User Information
- task: PowerShell@2
  displayName: "Set Git User Information"
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.name "Spucelik"
      git config --global user.email "steve@pucelik.net"



      # Commit and push changes to main branch
      git commit -m "Initial commit" || echo "No changes to commit"
      git branch -M main
      git push -u origin main
  env:
    GitHubToken: $(GitHubToken)
