# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    git remote add github https://github.com/Spucelik/Split-pages-from-a-document.git
    git push github main
  displayName: 'Push to GitHub'
